baseURL = "https://en.fernandafperes.com.br/"
languageCode = "pt-br"
defaultContentLanguage = "pt-br"
title = "Fernanda Peres | Estat√≠stica aplicada"
theme = "mediumish-gohugo-theme"
summaryLength = 25
copyright = "Fernanda Fiel Peres - Todos os direitos reservados"
enableEmoji = true
publishDir = "docs"
ignoreFiles = ['_bookdown.yml']
disqusShortname = "fernandafperes"
googleAnalytics = "G-ZBDS4LT6P0"


[params]
  logo = "/images/favicon.ico"
  description = ""
  customCSS = ["css/purebasic.css", "css/applause-button.css"]
  customJS = ["js/highlight.pack.js", "js/applause-button.js"]


[params.author]
  name = ""
  thumbnail = ""
  description = ""


[params.index]
  picture = "/images/author.png"
  title = "Fernanda Fiel Peres"
  subtitle = ""
  mdtext = '''
Currently trying to get this blog running, still don't know what the blog will be about!\
**This textblock is a demonstration of the mdtext-param.**\
### This is a markdown heading
'''
  alertbar = false

[params.social]
  github = "fernandaperes"
  linkedin = "fernandafielperes"
  instagram = "estatisticaaplicada"
  youtube = "c/FernandaPeres"

## Main Menu

[[menu.main]]
    name = "PT-BR"
    identifier = "language"
    weight = 5
    url = "https://fernandafperes.com.br"

[[menu.main]]
    name = "BLOG"
    weight = 20
    identifier = "blog"
    title = "Blog"
    url = "/blog"
    description = "Blog"

[[menu.main]]
    name = "ABOUT"
    identifier = "about"
    title = "About"
    weight = 30
    url = "/about"
    description = "About"

[[menu.main]]
    name = "HOME"
    identifier = "home"
    weight = 10
    url = "/"
